"""MineLib format read/write — ``.blocks`` / ``.prec`` / ``.upit``.

Formats follow the published library (verified against the live newman1 mirror):

- ``<name>.blocks`` — one row per block: ``id x y z <free columns>``; ids count from 0 in flat
  grid order; z is the LEVEL and increases upward. oreblocks writes three documented free
  columns: ``grade tonnage density`` (grade as a mass fraction).
- ``<name>.prec``   — one row per block: ``b n p_1 .. p_n`` (the n blocks that must be extracted
  before b).
- ``<name>.upit``   — the keyword header (NAME / TYPE / NBLOCKS / OBJECTIVE_FUNCTION:) then one
  ``b value`` row per block (net value at the optimal destination).

Instances written by oreblocks are SYNTHETIC and say so via the sidecar ``<name>.meta.json``
(seed, parameters, the stamped exact optimum, package version). Nothing here downloads or
redistributes published MineLib data.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from . import __version__ as _pkg_version
from .fields import Deposit
from .grid import BlockGrid
from .precedence import Precedence

__all__ = ["write_minelib", "read_blocks", "read_prec", "read_upit", "read_meta"]


def write_minelib(
    out_dir: str | Path,
    name: str,
    dep: Deposit,
    values: np.ndarray,
    prec: Precedence,
    *,
    meta_extra: dict | None = None,
) -> dict[str, Path]:
    """Write ``<name>.blocks/.prec/.upit`` (+ ``<name>.meta.json``) into ``out_dir``."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    g = dep.grid
    n = g.n_blocks
    if values.shape != (n,):
        raise ValueError(f"values must cover {n} blocks, got {values.shape}")

    ix, iy, level = g.coord_arrays()
    paths: dict[str, Path] = {}

    p_blocks = out / f"{name}.blocks"
    with p_blocks.open("w", encoding="ascii", newline="\n") as f:
        for b in range(n):
            f.write(
                f"{b} {ix[b]} {iy[b]} {level[b]} "
                f"{dep.grade[b]:.9g} {dep.tonnage[b]:.9g} {dep.density[b]:.9g}\n"
            )
    paths["blocks"] = p_blocks

    p_prec = out / f"{name}.prec"
    with p_prec.open("w", encoding="ascii", newline="\n") as f:
        for b in range(n):
            preds = prec.plist[prec.pstart[b] : prec.pstart[b + 1]]
            f.write(f"{b} {preds.shape[0]}" + "".join(f" {int(p)}" for p in preds) + "\n")
    paths["prec"] = p_prec

    p_upit = out / f"{name}.upit"
    with p_upit.open("w", encoding="ascii", newline="\n") as f:
        f.write(f"NAME: {name}\nTYPE: UPIT\nNBLOCKS: {n}\nOBJECTIVE_FUNCTION:\n")
        for b in range(n):
            f.write(f"{b} {values[b]:.9g}\n")
    paths["upit"] = p_upit

    meta = {
        "schema": "oreblocks.minelib-twin/v1",
        "synthetic": True,
        "statement": "SYNTHETIC instance generated by oreblocks — not a real mine, not MineLib data.",
        "oreblocks_version": _pkg_version,
        "grid": {"nx": g.nx, "ny": g.ny, "nz": g.nz, "dx": g.dx, "dy": g.dy, "dz": g.dz},
        "n_blocks": n,
        "n_precedence_arcs": prec.n_arcs,
        "blocks_free_columns": ["grade (mass fraction)", "tonnage (t)", "density (t/m3)"],
        **(dep.meta or {}),
        **(meta_extra or {}),
    }
    p_meta = out / f"{name}.meta.json"
    p_meta.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8", newline="\n")
    paths["meta"] = p_meta
    return paths


def _data_rows(text: str) -> list[list[str]]:
    rows = []
    for line in text.splitlines():
        t = line.split()
        if t and t[0].isdigit():
            rows.append(t)
    return rows


def read_blocks(path: str | Path) -> dict[str, np.ndarray]:
    """Read a ``.blocks`` file -> {'x','y','level','free'} (free = float matrix of extra cols)."""
    rows = _data_rows(Path(path).read_text(encoding="ascii"))
    n = len(rows)
    x = np.empty(n, dtype=np.int64)
    y = np.empty(n, dtype=np.int64)
    level = np.empty(n, dtype=np.int64)
    n_free = max(0, len(rows[0]) - 4) if rows else 0
    free = np.empty((n, n_free), dtype=np.float64)
    for r in rows:
        b = int(r[0])
        if not (0 <= b < n):
            raise ValueError(f".blocks: id {b} out of range (n={n})")
        x[b], y[b], level[b] = int(r[1]), int(r[2]), int(r[3])
        for k in range(n_free):
            free[b, k] = float(r[4 + k])
    return {"x": x, "y": y, "level": level, "free": free}


def read_prec(path: str | Path, n_blocks: int) -> Precedence:
    """Read a ``.prec`` file into the CSR Precedence layout."""
    rows = _data_rows(Path(path).read_text(encoding="ascii"))
    counts = np.zeros(n_blocks, dtype=np.int64)
    for r in rows:
        b, k = int(r[0]), int(r[1])
        if len(r) != 2 + k:
            raise ValueError(f".prec: row for {b} declares {k} preds but has {len(r) - 2}")
        counts[b] = k
    pstart = np.zeros(n_blocks + 1, dtype=np.int64)
    np.cumsum(counts, out=pstart[1:])
    plist = np.empty(int(pstart[-1]), dtype=np.int64)
    for r in rows:
        b = int(r[0])
        at = int(pstart[b])
        for j, tok in enumerate(r[2:]):
            p = int(tok)
            if not (0 <= p < n_blocks):
                raise ValueError(f".prec: predecessor {p} out of range for block {b}")
            plist[at + j] = p
    return Precedence(pstart=pstart, plist=plist)


def read_upit(path: str | Path, n_blocks: int) -> np.ndarray:
    """Read a ``.upit`` file (keyword header skipped) -> net values per block."""
    values = np.full(n_blocks, np.nan)
    for r in _data_rows(Path(path).read_text(encoding="ascii")):
        b = int(r[0])
        if not (0 <= b < n_blocks):
            raise ValueError(f".upit: id {b} out of range (n={n_blocks})")
        values[b] = float(r[1])
    if np.isnan(values).any():
        missing = int(np.isnan(values).sum())
        raise ValueError(f".upit: {missing} blocks have no value")
    return values


def read_meta(path: str | Path) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def grid_from_blocks(
    blocks: dict[str, np.ndarray], dx: float = 10.0, dy: float = 10.0, dz: float = 10.0
) -> BlockGrid:
    """Bounding-box grid implied by a ``.blocks`` table (dense instances only)."""
    return BlockGrid(
        nx=int(blocks["x"].max()) + 1,
        ny=int(blocks["y"].max()) + 1,
        nz=int(blocks["level"].max()) + 1,
        dx=dx,
        dy=dy,
        dz=dz,
    )
